### ISSUE TITLE
pga_dyn.html example is broken

### ISSUE THREAD

**Issue by riverbend305** [enkimute/ganja.js#144]
The pga_dyn.html example hangs during execution. 
I think the 'UnDual' operator is not defined.

To duplicate the issue:
Download ZIP 
cd  ./ganja.js-master/examples
open ./pga_dyn.html with Chrome Developer Tools

Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
highlight.min.js:106 Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
ganja.js:464 Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at Function.Mul (ganja.js:464:48)
    at dS (eval at inline (ganja.js:1661:16), <anonymous>:23:22)
    at c.graph.lineWidth (eval at inline (ganja.js:1661:16), <anonymous>:30:64)
    at Function.graph (ganja.js:686:40)
    at eval (eval at inline (ganja.js:1661:16), <anonymous>:27:16)
    at Algebra (ganja.js:1738:54)
    at window.Algebra (coffeeshop.js:15:30)
    at pga_dyn.html:331:1

**Comment by enkimute** [comment]
This uses some private features that have not yet been released - I hope to get at that next week.
