### ISSUE TITLE
Code generator fails to generate for R666 and similar

### ISSUE THREAD

**Issue by utensil** [enkimute/ganja.js#49]
Code generator fails to generate for R666 and similar, the error is:

```
make GEN_LANG="python" R666
CUSTOM METRIC :  6 6 6
~/ganja.js:542
      static lt(a,b)  { while(a.call)a=a(); while(b.call)b=b(); return (a instanceof Element?a.Length:a)<(b instanceof Element?b.Length:b); }
                                ^

TypeError: Cannot read property 'call' of undefined
    at Function.lt (~/ganja.js:542:33)
    at x.map (eval at inline (~/ganja.js:1256:16), <anonymous>:3:223)
    at Array.map (<anonymous>)
    at eval (eval at inline (~/ganja.js:1256:16), <anonymous>:3:102)
    at unops.map.u (~/ganja.js/codegen/generate.js:145:25)
    at Array.map (<anonymous>)
    at lang.filter.forEach.lang (~/ganja.js/codegen/generate.js:139:26)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (~/ganja.js/codegen/generate.js:125:35)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
make: *** [makefile:12: R666] Error 1
```

**Comment by enkimute** [comment]
Latest version of ganja and the codegen allows for the creation of these algebra's, although the generated sources quickly become to big for most compilers. (I would disadvise against using this strategy for anything over 8 dimensions.)
